"""Build the landing page as a thing you can touch, not a thing you read.

The previous page was documentation. A stranger with no geophysics landed on
dense text about Moho depths and mGal and left, correctly, because there was
nothing to do and nothing to see. Words cannot fix that; only something that
moves can.

So this page leads with the one idea that needs no domain knowledge at all:
four completely different pictures of what is underground, producing the same
readings. You can see it in two seconds without knowing what gravity is. Then
a slider lets you buy more survey and watch which parts stop being guesses.

Every number is generated by web/make_demo_data.py from the real engine.
Nothing here is a mock-up.

Run: py -3 web/make_demo_data.py && py -3 web/build_interactive.py
"""

import base64
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DATA = json.loads((ROOT / "web" / "demo_data.json").read_text())

REPO = "https://github.com/vaishak-v-nair/Gurutva"
# Vercel is the address; GitHub Pages serves the same bytes as a mirror, so
# both are canonicalised here to keep search engines and link unfurlers from
# treating them as two competing copies.
SITE = "https://gurutva.vercel.app"
# `releases/latest/download/<asset>` always resolves to the newest release
# carrying that asset name, so the page never has to be rebuilt to point at a
# new version. The asset name is therefore load-bearing: make_release.py
# checks it.
EXE_URL = f"{REPO}/releases/latest/download/Gurutva.exe"
_EXE = ROOT / "dist" / "onefile" / "Gurutva.exe"
EXE_MB = round(_EXE.stat().st_size / 1e6) if _EXE.exists() else 71
# The SHA-256 is deliberately NOT on the page any more (2026-08-04): a hash
# and a tamper-check instruction on a landing page read as a warning, and the
# people this page is for found it frightening rather than reassuring. The
# digest still ships in every release's notes, where the audience that wants
# it goes looking. make_release.py enforces the residual invariant: the page
# may carry no hash, but never a wrong one.

# The source zip is still built and still embedded: it is 61 KB, it needs
# Python, and it is what someone reads if they want to see what they are
# running before they run it. It is no longer the headline.
_ZIP = ROOT / "web" / "gurutva.zip"
ZIP_B64 = base64.b64encode(_ZIP.read_bytes()).decode()
ZIP_KB = round(_ZIP.stat().st_size / 1024)
N_TESTS = sum(len(re.findall(r"^def test_", f.read_text(encoding="utf-8"), re.M))
              for f in sorted((ROOT / "tests").glob("test_*.py")))
geo = json.loads((ROOT / "figures" / "verdict_geothermal.json").read_text())
ccs = json.loads((ROOT / "figures" / "verdict_carbon_storage.json").read_text())
dm = json.loads((ROOT / "figures" / "verdict_dark_matter.json").read_text())

CSS = """
:root{
  --ink:#12151a;--mut:#5d6670;--line:#dfe3e8;--paper:#fff;
  --ok:#0a7b52;--okbg:#e8f5ef;--okln:#b7e0cd;
  --no:#b3261e;--nobg:#fdeceb;--noln:#f3c4c0;
  --pv:#7a5200;--pvbg:#fdf4e3;--pvln:#e8d3a3;
  --disp:"Iowan Old Style","Sitka Text","Palatino Linotype",Palatino,Georgia,serif;
  --ui:"Söhne","Neue Haas Grotesk Text","Helvetica Neue",Helvetica,sans-serif;
}
@media (prefers-color-scheme:dark){:root{
  --ink:#e9ecef;--mut:#98a2ad;--line:#252a30;--paper:#0f1114;
  --ok:#5cd6a0;--okbg:#0e271d;--okln:#1e4936;
  --no:#ff7a6d;--nobg:#2b1512;--noln:#54251f;
  --pv:#e0b25c;--pvbg:#2a2113;--pvln:#4d3d1c;}}
:root[data-theme="dark"]{--ink:#e9ecef;--mut:#98a2ad;--line:#252a30;
  --paper:#0f1114;--ok:#5cd6a0;--okbg:#0e271d;--okln:#1e4936;--no:#ff7a6d;
  --nobg:#2b1512;--noln:#54251f;--pv:#e0b25c;--pvbg:#2a2113;--pvln:#4d3d1c;}
:root[data-theme="light"]{--ink:#12151a;--mut:#5d6670;--line:#dfe3e8;
  --paper:#fff;--ok:#0a7b52;--okbg:#e8f5ef;--okln:#b7e0cd;--no:#b3261e;
  --nobg:#fdeceb;--noln:#f3c4c0;--pv:#7a5200;--pvbg:#fdf4e3;--pvln:#e8d3a3;}
*{box-sizing:border-box}
html,body{max-width:100%;overflow-x:clip}
body{margin:0;background:var(--paper);color:var(--ink);
  font:18px/1.6 var(--disp);-webkit-font-smoothing:antialiased}
.wrap{max-width:1040px;margin:0 auto;padding:0 24px}
a{color:var(--ink);text-decoration:underline;text-decoration-thickness:2px;
  text-underline-offset:3px}
a:hover{text-decoration-thickness:3px}
a:focus-visible{outline:2px solid var(--ink);outline-offset:2px}
.num{font-variant-numeric:tabular-nums}
h2{font-family:var(--ui);font-size:12px;letter-spacing:.09em;
  text-transform:uppercase;color:var(--mut);font-weight:600;margin:0 0 18px}

header{padding:40px 0 0}
.hdr{display:flex;align-items:baseline;justify-content:space-between;gap:20px;
  flex-wrap:wrap}
.hdr-get{font-family:var(--ui);font-size:13px;font-weight:600;
  letter-spacing:.03em;text-decoration:none;border:1.5px solid var(--ink);
  padding:8px 14px;border-radius:6px;white-space:nowrap}
.hdr-get:hover{background:var(--ink);color:var(--paper)}
.brand{font-size:24px;letter-spacing:-.01em}
.brand span{color:var(--mut);font-family:var(--ui);font-size:13px;
  letter-spacing:.06em;text-transform:uppercase;margin-left:12px}

/* ---- act one: the four worlds ---- */
#hook{padding:56px 0 72px}
#hook h1{font-size:38px;line-height:1.22;letter-spacing:-.02em;margin:0 0 14px;
  max-width:20ch;text-wrap:balance}
#hook .sub{color:var(--mut);font-size:20px;max-width:52ch;margin:0 0 28px}
.worlds{display:grid;grid-template-columns:1.06fr repeat(4,1fr);gap:12px;
  align-items:end}
.worlds .truth canvas{border-color:var(--ink);border-width:2px}
.worlds .truth figcaption{color:var(--ink);font-weight:600}
.worlds .sep{border-left:1px solid var(--line);padding-left:12px}
.rep{display:block;margin-top:10px;font-family:var(--ui);font-size:12.5px;
  font-weight:600;text-decoration-thickness:1.5px}
.repnote{font-family:var(--ui);font-size:13px;color:var(--mut);
  margin:22px 0 0;max-width:70ch}
.worlds figure{margin:0}
.worlds canvas{width:100%;height:auto;display:block;border:1px solid var(--line);
  border-radius:6px;background:var(--paper)}
.worlds figcaption{font-family:var(--ui);font-size:11px;color:var(--mut);
  margin-top:6px;letter-spacing:.04em}
.readout{margin-top:22px;border:1px solid var(--line);border-radius:8px;
  padding:18px 20px}
.readout canvas{width:100%;height:auto;display:block}
.readout .cap{font-family:var(--ui);font-size:12.5px;color:var(--mut);
  margin-top:10px;line-height:1.55}
.punch{margin-top:26px;font-size:23px;max-width:46ch;letter-spacing:-.01em}
.punch b{color:var(--no)}

/* ---- act two: the slider ---- */
#play{padding:64px 0;border-top:1px solid var(--line)}
.play-grid{display:grid;grid-template-columns:1.15fr .85fr;gap:36px;
  align-items:start}
.play-grid>*{min-width:0}
#scene{width:100%;height:auto;display:block;border:1px solid var(--line);
  border-radius:8px;background:var(--paper)}
.ctl{margin-top:18px;font-family:var(--ui)}
.ctl label{display:block;font-size:12px;letter-spacing:.07em;
  text-transform:uppercase;color:var(--mut);margin-bottom:10px}
input[type=range]{width:100%;accent-color:var(--ink);height:28px}
.ticks{display:flex;justify-content:space-between;font-size:11px;
  color:var(--mut);margin-top:2px}
.badge{display:inline-block;font-family:var(--ui);font-size:11px;font-weight:700;
  letter-spacing:.09em;padding:5px 11px;border-radius:5px;margin-bottom:16px}
.b-ok{background:var(--okbg);color:var(--ok);border:1px solid var(--okln)}
.b-pv{background:var(--pvbg);color:var(--pv);border:1px solid var(--pvln)}
.b-no{background:var(--nobg);color:var(--no);border:1px solid var(--noln)}
.answer .v{font-size:40px;line-height:1.1;letter-spacing:-.02em}
.answer .r{color:var(--mut);font-size:17px;margin-top:6px}
.answer .t{margin-top:16px;font-size:16px;color:var(--mut);max-width:34em}
.legend{display:flex;gap:16px;font-family:var(--ui);font-size:11.5px;
  color:var(--mut);margin-top:12px;flex-wrap:wrap}
.sw{display:inline-block;width:11px;height:11px;border-radius:2px;
  margin-right:5px;vertical-align:-1px}

/* ---- act three ---- */
#says{padding:64px 0;border-top:1px solid var(--line)}
.states{display:grid;grid-template-columns:repeat(3,1fr);gap:20px}
.state{padding-top:14px;border-top:2px solid var(--line)}
.state.no{border-top-color:var(--no)}
.state.pv{border-top-color:var(--pv)}
.state.ok{border-top-color:var(--ok)}
.state h3{font-family:var(--ui);font-size:12px;letter-spacing:.09em;margin:0 0 8px}
.state p{margin:0;font-size:16px;color:var(--mut)}
.proof{margin-top:44px;display:grid;grid-template-columns:repeat(3,1fr);gap:24px}
.proof .n{font-size:26px;letter-spacing:-.01em;font-variant-numeric:tabular-nums}
.proof .k{font-family:var(--ui);font-size:11.5px;color:var(--mut);
  text-transform:uppercase;letter-spacing:.06em;margin-top:6px}
.proof .d{font-size:15px;color:var(--mut);margin-top:10px}

#start{padding:64px 0 40px;border-top:1px solid var(--line)}
.who{max-width:62ch;margin-bottom:18px;font-size:19px}
.get{display:inline-block;font-family:var(--ui);font-size:16px;font-weight:600;
  padding:13px 22px;border-radius:8px;border:2px solid var(--ink);
  text-decoration:none;letter-spacing:.01em}
.get:hover{background:var(--ink);color:var(--paper)}
.getline{margin-top:30px;display:flex;gap:16px;align-items:center;
  flex-wrap:wrap}
.getnote{font-family:var(--ui);font-size:13px;color:var(--mut);
  line-height:1.55;max-width:40ch}
.need{margin-top:14px;padding:12px 16px;border-left:3px solid var(--pvln);
  background:var(--pvbg);color:var(--pv);font-family:var(--ui);
  font-size:13.5px;border-radius:0 6px 6px 0;max-width:60ch}
.need code{background:transparent;padding:0;font-weight:700}
.how{margin-top:36px;border:1px solid var(--line);border-radius:8px;
  padding:22px 26px;max-width:64ch}
.how h3{font-family:var(--ui);font-size:12px;letter-spacing:.09em;
  text-transform:uppercase;color:var(--mut);margin:0 0 12px}
.how ol{margin:0;padding-left:22px;font-size:17px}
.how li{margin-bottom:9px}
.how code{background:var(--line);padding:2px 7px;border-radius:4px;
  font-size:15px;font-family:var(--ui)}
.how .whynot{margin:16px 0 0;font-size:15px;color:var(--mut)}
.contact{margin-top:32px;font-family:var(--ui);font-size:17px;line-height:2}
footer{border-top:1px solid var(--line);padding:22px 0 60px;
  font-family:var(--ui);font-size:12px;color:var(--mut);line-height:1.7}

@media (max-width:900px){
  .play-grid{grid-template-columns:1fr;gap:24px}
  .worlds{grid-template-columns:repeat(2,1fr)}
  .worlds .sep{border-left:0;padding-left:0}
  .states,.proof{grid-template-columns:1fr;gap:18px}
  #hook h1{font-size:29px}
  .punch{font-size:20px}
}
@media (prefers-reduced-motion:reduce){*{transition:none!important;
  animation:none!important}}
"""

JS = r"""
/* The .exe is 70 MB and cannot be a data URI, so the headline download is a
   real link to the GitHub release and needs no JS at all. Only the source
   zip is still embedded, for the reader who wants to see the code before
   running anything. */
document.querySelectorAll("[data-src-zip]").forEach(a =>
  a.href = "data:application/zip;base64," + __ZIP__);
const D = __DATA__;
const NX = D.nx, NZ = D.nz;

function ramp(v){                     // density contrast -> colour
  const t = Math.max(-1, Math.min(1, v / 0.5));
  if (t >= 0){ const a = t;
    return `rgb(${Math.round(255-60*a)},${Math.round(255-150*a)},${Math.round(255-165*a)})`; }
  const a = -t;
  return `rgb(${Math.round(255-165*a)},${Math.round(255-120*a)},${Math.round(255-40*a)})`;
}
function fit(cv, w, h){
  const dpr = window.devicePixelRatio || 1;
  cv.width = w * dpr; cv.height = h * dpr;
  cv.style.aspectRatio = w + " / " + h;
  const c = cv.getContext("2d"); c.setTransform(dpr,0,0,dpr,0,0); return c;
}
function drawSection(cv, vals, opts){
  opts = opts || {};
  const W = opts.w || 260, H = opts.h || 150, pad = opts.w ? 10 : 6;
  const c = fit(cv, W, H);
  const cw = (W - 2*pad) / NX, ch = (H - 2*pad - 14) / NZ;
  c.clearRect(0,0,W,H);
  for (let i=0;i<NX;i++) for (let k=0;k<NZ;k++){
    const v = vals[i*NZ + k];
    c.fillStyle = opts.mask ? shade(v, opts.mask[i*NZ+k]) : ramp(v);
    c.fillRect(pad + i*cw, pad + 14 + k*ch, cw+0.6, ch+0.6);
  }
  c.fillStyle = getComputedStyle(document.body).getPropertyValue("--mut");
  c.fillRect(pad, pad+12, W-2*pad, 1.2);          // the ground surface
  if (opts.stations){
    c.fillStyle = getComputedStyle(document.body).getPropertyValue("--ink");
    opts.stations.forEach(x=>{
      const px = pad + (x - D.x0)/(NX*D.cell) * (W-2*pad);
      c.beginPath(); c.arc(px, pad+8, 2.6, 0, 7); c.fill();
    });
  }
}
function shade(v, informed){          // grey out what the data does not know
  const g = Math.max(0, Math.min(1, informed/0.35));
  const base = ramp(v).match(/\d+/g).map(Number);
  const bg = document.documentElement.getAttribute("data-theme") === "dark"
    || (window.matchMedia("(prefers-color-scheme:dark)").matches
        && document.documentElement.getAttribute("data-theme") !== "light")
    ? [22,25,29] : [246,247,249];
  return `rgb(${base.map((b,i)=>Math.round(bg[i] + (b-bg[i])*g)).join(",")})`;
}
function drawReadings(cv, series, colours){
  const W = 700, H = 130, pad = 30;
  const c = fit(cv, W, H);
  c.clearRect(0,0,W,H);
  let lo = Infinity, hi = -Infinity;
  series.forEach(s=>s.forEach(v=>{lo=Math.min(lo,v);hi=Math.max(hi,v);}));
  const span = (hi-lo) || 1;
  const X = i => pad + i/(series[0].length-1) * (W-2*pad);
  const Y = v => H-pad - (v-lo)/span * (H-2*pad);
  const mut = getComputedStyle(document.body).getPropertyValue("--mut");
  c.strokeStyle = mut; c.globalAlpha=.35; c.lineWidth=1;
  c.beginPath(); c.moveTo(pad,H-pad); c.lineTo(W-pad,H-pad); c.stroke();
  c.globalAlpha=1;
  series.forEach((s,j)=>{
    c.strokeStyle = colours[j]; c.lineWidth = j===0 ? 3 : 1.6;
    c.globalAlpha = j===0 ? 1 : .85;
    c.beginPath(); s.forEach((v,i)=> i? c.lineTo(X(i),Y(v)) : c.moveTo(X(i),Y(v)));
    c.stroke();
  });
  c.globalAlpha=1;
}

/* ---- act one ---- */
const L0 = D.levels[D.levels.length-1];
drawSection(document.getElementById("wT"), D.truth);
["w0","w1","w2","w3"].forEach((id,i)=>
  drawSection(document.getElementById(id), L0.worlds[i]));
const ink = getComputedStyle(document.body).getPropertyValue("--ink");
drawReadings(document.getElementById("rd"),
  L0.world_readings, [ink, ink, ink, ink]);

/* ---- act two ---- */
const sl = document.getElementById("sl");
function update(){
  const L = D.levels[+sl.value];
  drawSection(document.getElementById("scene"), L.mean,
              {mask: L.informed, stations: L.station_x, w: 620, h: 330});
  document.getElementById("nst").textContent = L.n_station;
  const b = document.getElementById("badge");
  b.textContent = L.status;
  b.className = "badge " + (L.status==="CLAIMABLE" ? "b-ok"
                          : L.status==="PROVISIONAL" ? "b-pv" : "b-no");
  document.getElementById("val").textContent =
    (L.mass>=0?"+":"") + L.mass.toFixed(1) + " Mt";
  document.getElementById("rng").textContent =
    "could be anywhere from " + (L.mass-1.96*L.mass_sd).toFixed(1) +
    " to " + (L.mass+1.96*L.mass_sd).toFixed(1) + " Mt";
  const pct = Math.round(100*L.informed.filter(v=>v>0.05).length/L.informed.length);
  document.getElementById("inf").textContent = pct + "%";
}
sl.addEventListener("input", update);
update();
window.matchMedia("(prefers-color-scheme:dark)").addEventListener("change",()=>{
  ["w0","w1","w2","w3"].forEach((id,i)=>
    drawSection(document.getElementById(id), L0.worlds[i]));
  update();
});
"""


def build():
    js = (JS.replace("__DATA__", json.dumps(DATA, separators=(",", ":")))
            .replace("__ZIP__", json.dumps(ZIP_B64)))
    lo = geo["mass_Mt"] - 1.96 * geo["mass_sd_Mt"]
    hi = geo["mass_Mt"] + 1.96 * geo["mass_sd_Mt"]
    html = f"""<style>{CSS}</style>
<main>
<header><div class="wrap hdr">
  <div class="brand">Gurutva <span>how much of that picture is real?</span></div>
  <a class="hdr-get" href="{EXE_URL}">Download &nbsp;&darr;</a>
</div></header>

<section id="hook"><div class="wrap">
  <h1>We buried one block. Your survey cannot find it.</h1>
  <p class="sub">On the left is what is actually down there. We planted it, so
  the answer can be graded rather than argued about. The four beside it are
  what your readings still allow &mdash; every one of them reproduces the same
  measurements, to within twice the wobble of the instrument. Ordinary
  software picks one of them and draws it for you, in colour, with no
  warning.</p>

  <div class="worlds">
    <figure class="truth"><canvas id="wT"
      aria-label="The block that was actually buried"></canvas>
      <figcaption>What is really there</figcaption></figure>
    <figure class="sep"><canvas id="w0" aria-label="Underground picture 1"></canvas>
      <figcaption>Possibility 1</figcaption></figure>
    <figure><canvas id="w1" aria-label="Underground picture 2"></canvas>
      <figcaption>Possibility 2</figcaption></figure>
    <figure><canvas id="w2" aria-label="Underground picture 3"></canvas>
      <figcaption>Possibility 3</figcaption></figure>
    <figure><canvas id="w3" aria-label="Underground picture 4"></canvas>
      <figcaption>Possibility 4</figcaption></figure>
  </div>

  <div class="readout">
    <canvas id="rd" aria-label="The four sets of readings, lying on top of
      each other"></canvas>
    <div class="cap">All four sets of readings, on top of each other. They
    differ by at most <b class="num">0.111</b> &mdash; about twice the
    wobble of the instrument &mdash; while the pictures above differ by
    <b class="num">0.53 g/cc</b>, more than the entire body being
    hunted. Tiny differences up here, enormous differences down there. That
    is what makes this hard, and it does not go away by buying a better
    meter.</div>
  </div>

  <p class="punch">None of the four looks like the block. <b>That is not a
  bug in the software &mdash; it is what your data left undecided.</b> Which
  is itself measurable, and almost nothing in this industry reports it.</p>

  <div class="getline">
    <a class="get" href="{EXE_URL}">Download for Windows &nbsp;&darr;</a>
    <span class="getnote">{EXE_MB}&nbsp;MB. Double-click it. Runs on your
      laptop; your survey is never uploaded anywhere.</span>
  </div>
  <div class="need">No Python, no install, no admin rights. The first time
    you open it, Windows asks you to confirm: click <b>More&nbsp;info</b>,
    then <b>Run&nbsp;anyway</b>, and it starts. Prefer to read the source
    first? <a data-src-zip href="#get" download="gurutva.zip">The
    {ZIP_KB}&nbsp;KB Python version</a> is the same code, and needs
    <code>numpy scipy matplotlib</code>.</div>
</div></section>

<section id="play"><div class="wrap">
  <h2>What buying more survey actually buys you</h2>
  <div class="play-grid">
    <div>
      <canvas id="scene" aria-label="Cross-section: colour where the data
        knows, faded where it is guessing"></canvas>
      <div class="legend">
        <span><span class="sw" style="background:#c94a3c"></span>dense rock</span>
        <span><span class="sw" style="background:#4a78c9"></span>light rock</span>
        <span><span class="sw" style="background:#b9bec4"></span>faded = the
          software is guessing here</span>
        <span>&bull; sensors</span>
      </div>
      <div class="ctl">
        <label for="sl">Sensors on the ground: <b id="nst" class="num"></b></label>
        <input id="sl" type="range" min="0" max="{len(DATA['levels'])-1}"
               value="{len(DATA['levels'])-1}" step="1">
        <div class="ticks"><span>4 &mdash; cheap</span><span>30 &mdash; thorough</span></div>
      </div>
    </div>
    <div class="answer">
      <span id="badge" class="badge"></span>
      <div class="v num" id="val"></div>
      <div class="r num" id="rng"></div>
      <div class="t">That range is the product. Drag the slider: the picture
      does not change much, but how much of it is <em>real</em> does. Right now
      the data actually constrains <b id="inf" class="num"></b> of it &mdash;
      the rest is the software filling in.</div>
      <div class="t">Every number here comes from the real engine, on a scene
      where we planted the answer, so the checks can be graded honestly.</div>
    </div>
  </div>
</div></section>

<section id="says"><div class="wrap">
  <h2>Three things it is allowed to say</h2>
  <div class="states">
    <div class="state no"><h3>NOT CLAIMED</h3>
      <p>A check failed. The numbers are diagnostics. Do not put them in a
      decision.</p></div>
    <div class="state pv"><h3>PROVISIONAL</h3>
      <p>Every check passed, but nothing was compared against a known right
      answer &mdash; because real data has none.</p></div>
    <div class="state ok"><h3>CLAIMABLE</h3>
      <p>Every check passed <em>and</em> it was verified against a known
      answer. Rare, and meant to be.</p></div>
  </div>

  <div class="proof">
    <div><div class="n num">{geo['mass_Mt']:+,.0f} Mt</div>
      <div class="k">Utah FORGE &middot; real DOE data</div>
      <div class="d">95% between {lo:+,.0f} and {hi:+,.0f}. The standard
      workflow would have called this interval
      {geo['overconfidence_factor']:.1f}&times; tighter than it is.
      <a class="rep" href="reports/verdict_geothermal.html">Read the whole
      report &rarr;</a></div></div>
    <div><div class="n num">72%</div>
      <div class="k">CO&#8322; containment</div>
      <div class="d">A 400 m leak two kilometres out is only detectable above
      72% saturation. Below that, no containment claim covers it &mdash; and
      we say so instead of quoting a number.
      <a class="rep" href="reports/verdict_carbon_storage.html">Read the whole
      report &rarr;</a></div></div>
    <div><div class="n num">{dm['peak_sigma']:.1f}&sigma;</div>
      <div class="k">A dark-matter halo</div>
      <div class="d">The same code, unchanged, at 10<sup>22</sup> times the
      distance. All four checks passed and the fifth caught it anyway, so the
      map is <em>not claimed</em>.
      <a class="rep" href="reports/verdict_dark_matter.html">Read the whole
      report &rarr;</a></div></div>
  </div>
  <p class="repnote">Those are the actual documents the tool writes, not
  summaries of them. The gate rows, the refusals and the figures are exactly
  what lands next to your data.</p>
</div></section>

<section id="start"><div class="wrap">
  <h2>Who this is for</h2>
  <p class="who"><b>You are about to drill.</b> Get the range, and the depth
  below which the picture is invented, before the rig moves.</p>
  <p class="who"><b>You store CO&#8322; and have to prove it stayed put.</b>
  Get a defensible statement of what your monitoring can and cannot show
  &mdash; before you fund it.</p>
  <p class="who"><b>You want to check the work.</b> {N_TESTS} passing tests,
  and the retractions are in there too. The code is
  <a href="{REPO}">public, under Apache&#8209;2.0</a>.</p>

  <div class="how">
    <h3>How you actually use it</h3>
    <ol>
      <li>Download <code>Gurutva.exe</code> and double-click it. There is no
        step two: no Python, no install, no admin rights.</li>
      <li>Press <b>Use the example</b>, then <b>Run</b>, to watch it work on
        a survey that ships inside it.</li>
      <li>Then choose your own CSV and answer three questions about your
        site. We do not guess them for you: they are statements about your
        ground, not ours.</li>
      <li>A report opens in your browser, saved next to your data.</li>
    </ol>
    <p class="getline"><a class="get" href="{EXE_URL}">Download
       Gurutva.exe &nbsp;&darr;</a></p>
    <p class="whynot">There is no sign-up, no upload, and no server. It runs
    on your laptop and your data never leaves it. If a check fails it will
    tell you so and refuse to give you a number &mdash; that is the product,
    not a fault.</p>
  </div>

  <p class="contact">
    <a href="{REPO}/issues">Tell me what broke &mdash; github.com/vaishak-v-nair/Gurutva/issues</a>
  </p>
</div></section>

<footer><div class="wrap">
  Gurutva &middot; Bayesian uncertainty for gravity and magnetic surveys.
  The four possibilities above are posterior samples from the real engine, not
  illustrations. Source at <a href="{REPO}">github.com/vaishak-v-nair/Gurutva</a>,
  Apache&#8209;2.0. No tracking, no cookies.
</div></footer>
</main>
<script>{js}</script>
"""
    # For a year this page was a fragment: the artifact host wrapped it in a
    # document and supplied the head. Served from GitHub Pages the fragment IS
    # the document, and the live page had no doctype (quirks mode), no title,
    # and — the one that actually mattered — no viewport meta, so every phone
    # laid it out at 980px and scaled the result down. Found by loading the
    # published URL, not by reading this file.
    html = f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Gurutva — how much of that picture is real?</title>
<meta name="description" content="Gravity surveys decide where to drill and
whether stored CO2 stayed put. Gurutva computes which parts of that picture
your data actually support, and refuses to answer when it cannot.">
<meta name="theme-color" content="#faf8f4"
      media="(prefers-color-scheme: light)">
<meta name="theme-color" content="#0f1114"
      media="(prefers-color-scheme: dark)">
<meta property="og:type" content="website">
<meta property="og:title" content="Gurutva — gravity, with error bars">
<meta property="og:description" content="Inversion software draws you one
picture of what is underground. Gurutva tells you which parts your data
actually support, and refuses to answer when it cannot.">
<meta property="og:url" content="{SITE}/">
<meta property="og:image"
      content="{SITE}/social-preview.png">
<meta property="og:image:width" content="1280">
<meta property="og:image:height" content="640">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:image"
      content="{SITE}/social-preview.png">
<link rel="canonical" href="{SITE}/">
</head>
<body>
{html}
</body>
</html>
"""

    out = ROOT / "web" / "index.html"
    out.write_text(html, encoding="utf-8")
    print(f"wrote {out}  ({len(html)/1024:.0f} KB, {N_TESTS} tests)")

    # GitHub Pages serves main:/docs. Writing the same bytes to both keeps
    # web/ as the source of truth and makes the published page a build
    # artifact rather than a file anyone edits by hand.
    pages = ROOT / "docs" / "index.html"
    pages.write_text(html, encoding="utf-8")
    # Pages runs Jekyll by default, which silently drops files and folders
    # beginning with an underscore. Nothing here starts with one today, and
    # this is the one-line insurance against that changing.
    (ROOT / "docs" / ".nojekyll").write_text("", encoding="utf-8")
    print(f"wrote {pages}  (GitHub Pages: main branch, /docs)")


if __name__ == "__main__":
    build()
